### ISSUE TITLE
Share external users

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/web-ui#116]
This epic contains all external share-related issues:
### web-ui:
- [x]  Create a floating card with the following steps:
1. Choose approvers (with regular auto-complete).
2. Choose approvers (external auto-complete).
3. Add info and choose classification.
* On submit, the permits will be created and the user will wait for a response.
- issue: #109 

### approval-service:
- [x] Create a status table page to watch the progress of the statuses of the shares.
* add the link to the table by href/ iframe/...

### permit-service:
- [ ] Update all statuses of the requests when restarted: 
1. Go over all of the requests with status which is not final (Approved/Declined/...).
2. Check with status-service if any of the statuses changed.
3. Update the db.

### api-gateway:
- [ ]

**Comment by Shahar-Y** [comment]
Closing with #135 . The last part will have an issue in permit-service
