### ISSUE TITLE
View external shared files

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/web-ui#117]
Distinguish from externally-shared files. The separation will require:

### web-ui:
- [ ] on the 'shared with me' tab, create the same separation as in files vs folders.
The separation will be with a retrieved flag from api-gateway.
-> getSharedWithMe function in the files.js file.

- [x] on the 'info' of the file, mark with a different color the external users. 

### api-gateway:
- [x] Add a field of external shares vs. regular shares by the sharer id (found in delegation-service vs user-service). 
-> This is added to the /api/files?shares api.
